// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: api/deploy.proto

package api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeployListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     uint32 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize uint32 `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *DeployListReq) Reset() {
	*x = DeployListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_deploy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployListReq) ProtoMessage() {}

func (x *DeployListReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_deploy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployListReq.ProtoReflect.Descriptor instead.
func (*DeployListReq) Descriptor() ([]byte, []int) {
	return file_api_deploy_proto_rawDescGZIP(), []int{0}
}

func (x *DeployListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DeployListReq) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type DeployListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*DeployListRsp_Row `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
}

func (x *DeployListRsp) Reset() {
	*x = DeployListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_deploy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployListRsp) ProtoMessage() {}

func (x *DeployListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_deploy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployListRsp.ProtoReflect.Descriptor instead.
func (*DeployListRsp) Descriptor() ([]byte, []int) {
	return file_api_deploy_proto_rawDescGZIP(), []int{1}
}

func (x *DeployListRsp) GetList() []*DeployListRsp_Row {
	if x != nil {
		return x.List
	}
	return nil
}

type DeployCreateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Image string `protobuf:"bytes,2,opt,name=Image,proto3" json:"Image,omitempty"`
}

func (x *DeployCreateReq) Reset() {
	*x = DeployCreateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_deploy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployCreateReq) ProtoMessage() {}

func (x *DeployCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_deploy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployCreateReq.ProtoReflect.Descriptor instead.
func (*DeployCreateReq) Descriptor() ([]byte, []int) {
	return file_api_deploy_proto_rawDescGZIP(), []int{2}
}

func (x *DeployCreateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployCreateReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type DeployCreateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeployCreateRsp) Reset() {
	*x = DeployCreateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_deploy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployCreateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployCreateRsp) ProtoMessage() {}

func (x *DeployCreateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_deploy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployCreateRsp.ProtoReflect.Descriptor instead.
func (*DeployCreateRsp) Descriptor() ([]byte, []int) {
	return file_api_deploy_proto_rawDescGZIP(), []int{3}
}

type DeployUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Image string `protobuf:"bytes,3,opt,name=Image,proto3" json:"Image,omitempty"`
}

func (x *DeployUpdateReq) Reset() {
	*x = DeployUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_deploy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployUpdateReq) ProtoMessage() {}

func (x *DeployUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_deploy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployUpdateReq.ProtoReflect.Descriptor instead.
func (*DeployUpdateReq) Descriptor() ([]byte, []int) {
	return file_api_deploy_proto_rawDescGZIP(), []int{4}
}

func (x *DeployUpdateReq) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *DeployUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployUpdateReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type DeployUpdateRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeployUpdateRsp) Reset() {
	*x = DeployUpdateRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_deploy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployUpdateRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployUpdateRsp) ProtoMessage() {}

func (x *DeployUpdateRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_deploy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployUpdateRsp.ProtoReflect.Descriptor instead.
func (*DeployUpdateRsp) Descriptor() ([]byte, []int) {
	return file_api_deploy_proto_rawDescGZIP(), []int{5}
}

type DeployDeleteReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *DeployDeleteReq) Reset() {
	*x = DeployDeleteReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_deploy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployDeleteReq) ProtoMessage() {}

func (x *DeployDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_deploy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployDeleteReq.ProtoReflect.Descriptor instead.
func (*DeployDeleteReq) Descriptor() ([]byte, []int) {
	return file_api_deploy_proto_rawDescGZIP(), []int{6}
}

func (x *DeployDeleteReq) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeployDeleteRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeployDeleteRsp) Reset() {
	*x = DeployDeleteRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_deploy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployDeleteRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployDeleteRsp) ProtoMessage() {}

func (x *DeployDeleteRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_deploy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployDeleteRsp.ProtoReflect.Descriptor instead.
func (*DeployDeleteRsp) Descriptor() ([]byte, []int) {
	return file_api_deploy_proto_rawDescGZIP(), []int{7}
}

type DeployListRsp_Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Image string `protobuf:"bytes,2,opt,name=Image,proto3" json:"Image,omitempty"`
}

func (x *DeployListRsp_Row) Reset() {
	*x = DeployListRsp_Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_deploy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeployListRsp_Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployListRsp_Row) ProtoMessage() {}

func (x *DeployListRsp_Row) ProtoReflect() protoreflect.Message {
	mi := &file_api_deploy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployListRsp_Row.ProtoReflect.Descriptor instead.
func (*DeployListRsp_Row) Descriptor() ([]byte, []int) {
	return file_api_deploy_proto_rawDescGZIP(), []int{1, 0}
}

func (x *DeployListRsp_Row) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployListRsp_Row) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

var File_api_deploy_proto protoreflect.FileDescriptor

var file_api_deploy_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0d, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x50, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x6c, 0x0a, 0x0d, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x1a, 0x2f, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x22, 0x3b, 0x0a, 0x0f, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x73, 0x70, 0x22, 0x4b, 0x0a, 0x0f, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x73, 0x70, 0x22, 0x21, 0x0a, 0x0f, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x64, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x65, 0x70, 0x6c, 0x6f,
	0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x73, 0x70, 0x32, 0xb8, 0x02, 0x0a, 0x06, 0x44,
	0x65, 0x70, 0x6c, 0x6f, 0x79, 0x12, 0x44, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f,
	0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x4c, 0x0a, 0x06, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x73,
	0x70, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22, 0x0e, 0x2f, 0x64, 0x65, 0x70, 0x6c,
	0x6f, 0x79, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x73, 0x70, 0x22,
	0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22, 0x0e, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79,
	0x2f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x73, 0x70, 0x22, 0x16, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22, 0x0e, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2f, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x6f, 0x75, 0x63, 0x68, 0x75, 0x6e, 0x78, 0x75, 0x2f, 0x67, 0x6f,
	0x66, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_deploy_proto_rawDescOnce sync.Once
	file_api_deploy_proto_rawDescData = file_api_deploy_proto_rawDesc
)

func file_api_deploy_proto_rawDescGZIP() []byte {
	file_api_deploy_proto_rawDescOnce.Do(func() {
		file_api_deploy_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_deploy_proto_rawDescData)
	})
	return file_api_deploy_proto_rawDescData
}

var file_api_deploy_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_deploy_proto_goTypes = []interface{}{
	(*DeployListReq)(nil),     // 0: api.DeployListReq
	(*DeployListRsp)(nil),     // 1: api.DeployListRsp
	(*DeployCreateReq)(nil),   // 2: api.DeployCreateReq
	(*DeployCreateRsp)(nil),   // 3: api.DeployCreateRsp
	(*DeployUpdateReq)(nil),   // 4: api.DeployUpdateReq
	(*DeployUpdateRsp)(nil),   // 5: api.DeployUpdateRsp
	(*DeployDeleteReq)(nil),   // 6: api.DeployDeleteReq
	(*DeployDeleteRsp)(nil),   // 7: api.DeployDeleteRsp
	(*DeployListRsp_Row)(nil), // 8: api.DeployListRsp.Row
}
var file_api_deploy_proto_depIdxs = []int32{
	8, // 0: api.DeployListRsp.List:type_name -> api.DeployListRsp.Row
	0, // 1: api.Deploy.List:input_type -> api.DeployListReq
	2, // 2: api.Deploy.Create:input_type -> api.DeployCreateReq
	4, // 3: api.Deploy.Update:input_type -> api.DeployUpdateReq
	6, // 4: api.Deploy.Delete:input_type -> api.DeployDeleteReq
	1, // 5: api.Deploy.List:output_type -> api.DeployListRsp
	3, // 6: api.Deploy.Create:output_type -> api.DeployCreateRsp
	5, // 7: api.Deploy.Update:output_type -> api.DeployUpdateRsp
	7, // 8: api.Deploy.Delete:output_type -> api.DeployDeleteRsp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_deploy_proto_init() }
func file_api_deploy_proto_init() {
	if File_api_deploy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_deploy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_deploy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_deploy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployCreateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_deploy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployCreateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_deploy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_deploy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployUpdateRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_deploy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployDeleteReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_deploy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployDeleteRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_deploy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeployListRsp_Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_deploy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_deploy_proto_goTypes,
		DependencyIndexes: file_api_deploy_proto_depIdxs,
		MessageInfos:      file_api_deploy_proto_msgTypes,
	}.Build()
	File_api_deploy_proto = out.File
	file_api_deploy_proto_rawDesc = nil
	file_api_deploy_proto_goTypes = nil
	file_api_deploy_proto_depIdxs = nil
}
