// Code generated by protoc-gen-gin. DO NOT EDIT.

package api

import (
	context "context"
	gin "github.com/gin-gonic/gin"
	api_errors "github.com/zouchunxu/gof/pkg/api_errors"
	responses "github.com/zouchunxu/gof/pkg/responses"
	http "net/http"
	reflect "reflect"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(http.Request)
var _ = new(context.Context)
var _ = new(gin.Engine)
var _ = responses.New
var _ = api_errors.New
var _ = reflect.ValueOf

type GreetHandler interface {
	SayHello(context.Context, *SayHelloReq) (*SayHelloRsp, error)
}

func NewGreetHandler(srv GreetHandler, route *gin.Engine) {

	route.Handle("GET", "/say/hello", func(c *gin.Context) {
		var in SayHelloReq
		if "GET" == "GET" {
			if err := c.ShouldBindQuery(&in); err != nil {
				c.JSON(200, responses.New(500, nil, err.Error()))
				return
			}
		} else {
			if err := c.ShouldBindJSON(&in); err != nil {
				c.JSON(200, responses.New(500, nil, err.Error()))
				return
			}
		}

		ctx := context.Background()
		out, err := srv.SayHello(ctx, &in)
		if err != nil {
			if apiError, ok := err.(*api_errors.ApiError); ok {
				c.JSON(200, responses.New(apiError.Code(), apiError.Data(), apiError.Message()))
				return
			}
			c.JSON(200, err.Error())
			return
		}
		c.JSON(200, responses.New(0, out, "ok"))
	})

}
