apiVersion: apps/v1
kind: Deployment
metadata:
  name: gof-deploy
spec:
  selector:
    matchLabels:
      app: gof-deploy
  replicas: 2
  template:
    metadata:
      labels:
        app: gof-deploy
    spec:
      containers:
      - name: gof-deploy
        image: gof-deploy:1.0
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5903
        - containerPort: 5904
        - containerPort: 9909
        - containerPort: 5906

---

apiVersion: v1
kind: Service
metadata:
  name: gof-deploy
  labels:
    app: gof-deploy
spec:
  ports:
    - port: 5903
      name: grpc
    - port: 5904
      name: prometheus
    - port: 5906
      name: http
  clusterIP: None
  selector:
    app: gof-deploy
